import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language =
  | "English"
  | "Hindi"
  | "Bengali"
  | "Telugu"
  | "Marathi"
  | "Tamil"
  | "Urdu"
  | "Gujarati"
  | "Kannada"
  | "Malayalam"
  | "Odia"
  | "Punjabi"
  | "Assamese";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, defaultText: string) => string; // Placeholder for future string translation
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  English: {
    "Engineer View": "Engineer View",
    "Manager View": "Manager View",
    "AI Insights": "AI Insights",
    "Powered by Gemini": "Powered by Gemini",
    "Technical Summary": "Technical Summary",
    "Key Specifications": "Key Specifications",
    "Compliance Status": "Compliance Status",
    "Risk Factors": "Risk Factors",
    "Executive Summary": "Executive Summary",
    "Financial Overview": "Financial Overview",
    "Risk Assessment": "Risk Assessment",
    "Recommended Actions": "Recommended Actions",
    "Export Summary": "Export Summary",
    "Share Insights": "Share Insights",
    "Regenerate": "Regenerate",
    "View Original": "View Original",
    // Navigation & Settings
    "Settings": "Settings",
    "Language & Region": "Language & Region",
    "Interface Language": "Interface Language",
    "Select your preferred language for the application interface.": "Select your preferred language for the application interface.",
    "Note: AI Insights language is managed separately within the Document Viewer.": "Note: AI Insights language is managed separately within the Document Viewer.",
    "Select Language": "Select Language",
    "Current": "Current",
    "Appearance": "Appearance",
    "Theme selection (Dark/Light) is currently managed by the system.": "Theme selection (Dark/Light) is currently managed by the system.",
    "Dashboard": "Dashboard",
    "Search": "Search",
    "Profile": "Profile",
    "Logout": "Logout",
    "Admin Panel": "Admin Panel",
    "Language": "Language",
    // Sidebar
    "Documents": "Documents",
    "IoT Dashboard": "IoT Dashboard",
    "Knowledge Graph": "Knowledge Graph",
    "AR Visualization": "AR Visualization",
    "Compliance": "Compliance",
    "Features": "Features",
    "New": "New",
    // Dashboard & Widgets
    "Morning Briefing": "Morning Briefing",
    "Here's what you need to know today": "Here's what you need to know today",
    "System Status": "System Status",
    "Operational": "Operational",
    "Active Nodes": "Active Nodes",
    "Verification Rate": "Verification Rate",
    "Pending Review": "Pending Review",
    "Recent Activity": "Recent Activity",
    "Upload Document": "Upload Document",
    "View": "View",
    "Upload": "Upload",
    "Processing": "Processing",
    "Completed": "Completed",
    "Failed": "Failed",
    // Document Library
    "All Documents": "All Documents",
    "Uploaded by Me": "Uploaded by Me",
    "Shared with Me": "Shared with Me",
    "Filter by Type": "Filter by Type",
    "No documents found": "No documents found",
    "Try different keywords": "Try different keywords",
    "Drop files here": "Drop files here",
    "or click to browse": "or click to browse",
    "Supported formats": "Supported formats",
    "Upload Progress": "Upload Progress",
    "Recent": "Recent",
    "Favorites": "Favorites",
    "Archive": "Archive",
    "Sort by": "Sort by",
    "Date": "Date",
    "Name": "Name",
    "Size": "Size",
    "Type": "Type",
    // Forms & Modals
    "Save": "Save",
    "Cancel": "Cancel",
    "Delete": "Delete",
    "Edit": "Edit",
    "Close": "Close",
    "Submit": "Submit",
    "Reset": "Reset",
    "Apply": "Apply",
    "Confirm": "Confirm",
    "Are you sure?": "Are you sure?",
    "This action cannot be undone": "This action cannot be undone",
    "Email": "Email",
    "Description": "Description",
    "Tags": "Tags",
    "Category": "Category",
    "Comments": "Comments",
    "Attachment": "Attachment",
    // Validation & Errors
    "Required field": "Required field",
    "Invalid format": "Invalid format",
    "Invalid email": "Invalid email",
    "Connection failed": "Connection failed",
    "Not found": "Not found",
    "Unauthorized": "Unauthorized",
    "Something went wrong": "Something went wrong",
    "Please try again": "Please try again",
    "Error loading data": "Error loading data",
    // Success Messages
    "Saved successfully": "Saved successfully",
    "Updated successfully": "Updated successfully",
    "Deleted successfully": "Deleted successfully",
    "Uploaded successfully": "Uploaded successfully",
    "Changes saved": "Changes saved",
    // Compliance
    "Compliant": "Compliant",
    "Non-Compliant": "Non-Compliant",
    "Under Review": "Under Review",
    "Approve": "Approve",
    "Reject": "Reject",
    "Request Changes": "Request Changes",
    "Compliance Status": "Compliance Status",
    "Audit Trail": "Audit Trail",
    "Violations": "Violations",
    // IoT Dashboard  
    "Devices": "Devices",
    "Sensors": "Sensors",
    "Alerts": "Alerts",
    "Status": "Status",
    "Temperature": "Temperature",
    "Pressure": "Pressure",
    "Humidity": "Humidity",
    "Voltage": "Voltage",
    "Online": "Online",
    "Offline": "Offline",
    "Warning": "Warning",
    "Critical": "Critical",
    // Knowledge Graph
    "Nodes": "Nodes",
    "Connections": "Connections",
    "Topics": "Topics",
    "People": "People",
    "Expand": "Expand",
    "Collapse": "Collapse",
    "Export": "Export",
    "Zoom In": "Zoom In",
    "Zoom Out": "Zoom Out",
    // Workforce
    "Active": "Active",
    "Inactive": "Inactive",
    "On Leave": "On Leave",
    "Departed": "Departed",
    "View Profile": "View Profile",
    "Assign Task": "Assign Task",
    "Send Message": "Send Message",
    "Department": "Department",
    "Role": "Role",
    "Location": "Location",
    // Tooltips & Actions
    "Click to expand": "Click to expand",
    "Drag to reorder": "Drag to reorder",
    "Right-click for options": "Right-click for options",
    "Loading...": "Loading...",
    "Refresh": "Refresh",
    "Download": "Download",
    "Print": "Print",
    "Share": "Share",
    "Copy": "Copy",
    "Paste": "Paste",
    "Duplicate": "Duplicate",
    "More actions": "More actions"
  },
  Hindi: {
    "Engineer View": "इंजीनियर व्यू",
    "Manager View": "मैनेजर व्यू",
    "AI Insights": "AI इनसाइट्स",
    "Powered by Gemini": "जेमिनी द्वारा संचालित",
    "Technical Summary": "तकनीकी सारांश",
    "Key Specifications": "मुख्य विनिर्देश",
    "Compliance Status": "अनुपालन स्थिति",
    "Risk Factors": "जोखिम कारक",
    "Executive Summary": "कार्यकारी सारांश",
    "Financial Overview": "विततीय अवलोकन",
    "Risk Assessment": "जोखिम मूल्यांकन",
    "Recommended Actions": "अनुशंसित कार्रवाई",
    "Export Summary": "सारांश निर्यात करें",
    "Share Insights": "इनसाइट्स साझा करें",
    "Regenerate": "पुनः उत्पन्न करें",
    "View Original": "मूल देखें",
    // Navigation & Settings
    "Settings": "सेटिंग्स",
    "Language & Region": "भाषा और क्षेत्र",
    "Interface Language": "इंटरफ़ेस भाषा",
    "Select your preferred language for the application interface.": "एप्लिकेशन इंटरफ़ेस के लिए अपनी पसंदीदा भाषा चुनें।",
    "Note: AI Insights language is managed separately within the Document Viewer.": "नोट: AI इनसाइट्स की भाषा दस्तावेज़ व्यूअर के भीतर अलग से प्रबंधित की जाती है।",
    "Select Language": "भाषा चुनें",
    "Current": "वर्तमान",
    "Appearance": "दिखावट",
    "Theme selection (Dark/Light) is currently managed by the system.": "थीम चयन (डार्क/लाइट) वर्तमान में सिस्टम द्वारा प्रबंधित किया जाता है।",
    "Dashboard": "डैशबोर्ड",
    "Search": "खोजें",
    "Profile": "प्रोफ़ाइल",
    "Logout": "लॉग आउट",
    "Admin Panel": "एडमिन पैनल",
    "Language": "भाषा",
    // Sidebar
    "Documents": "दस्तावेज़",
    "IoT Dashboard": "प्रौद्योगिकी डैशबोर्ड", // IoT Dashboard
    "Knowledge Graph": "ज्ञान ग्राफ", // Knowledge Graph
    "AR Visualization": "AR विज़ुअलाइज़ेशन",
    "Compliance": "अनुपालन",
    "Features": "विशेषताएं",
    "New": "नया",
    // Dashboard & Widgets
    "Morning Briefing": "सुबह की जानकारी", // Morning Briefing
    "Here's what you need to know today": "आज आपको जो जानने की जरूरत है",
    "System Status": "सिस्टम स्थिति",
    "Operational": "परिचालन",
    "Active Nodes": "सक्रिय नोड्स",
    "Verification Rate": "सत्यापन दर",
    "Pending Review": "समीक्षा लंबित",
    "Recent Activity": "हाल की गतिविधि",
    "Upload Document": "दस्तावेज़ अपलोड करें",
    "View": "देखें",
    "Upload": "अपलोड",
    "Processing": "प्रोसेसिंग",
    "Completed": "पूर्ण",
    "Failed": "विफल",
    // Document Library
    "All Documents": "सभी दस्तावेज़",
    "Uploaded by Me": "मेरे द्वारा अपलोड किए गए",
    "Shared with Me": "मेरे साथ साझा किए गए",
    "Filter by Type": "प्रकार के अनुसार फ़िल्टर करें",
    "No documents found": "कोई दस्तावेज़ नहीं मिला",
    "Try different keywords": "विभिन्न कीवर्ड आज़माएं",
    "Drop files here": "फ़ाइलें यहां छोड़ें",
    "or click to browse": "या ब्राउज़ करने के लिए क्लिक करें",
    "Supported formats": "समर्थित प्रारूप",
    "Upload Progress": "अपलोड प्रगति",
    "Recent": "हाल का",
    "Favorites": "पसंदीदा",
    "Archive": "संग्रह",
    "Sort by": "इसके अनुसार क्रमबद्ध करें",
    "Date": "तारीख",
    "Name": "नाम",
    "Size": "आकार",
    "Type": "प्रकार",
    // Forms & Modals
    "Save": "सहेजें",
    "Cancel": "रद्द करें",
    "Delete": "हटाएं",
    "Edit": "संपादित करें",
    "Close": "बंद करें",
    "Submit": "सबमिट करें",
    "Reset": "रीसेट करें",
    "Apply": "लागू करें",
    "Confirm": "पुष्टि करें",
    "Are you sure?": "क्या आप सुनिश्चित हैं?",
    "This action cannot be undone": "इस क्रिया को वापस नहीं किया जा सकता",
    "Email": "ईमेल",
    "Description": "विवरण",
    "Tags": "टैग",
    "Category": "श्रेणी",
    "Comments": "टिप्पणियां",
    "Attachment": "अनुलग्नक",
    // Validation & Errors
    "Required field": "आवश्यक फ़ील्ड",
    "Invalid format": "अमान्य प्रारूप",
    "Invalid email": "अमान्य ईमेल",
    "Connection failed": "कनेक्शन विफल",
    "Not found": "नहीं मिला",
    "Unauthorized": "अनधिकृत",
    "Something went wrong": "कुछ गलत हो गया",
    "Please try again": "कृपया पुन: प्रयास करें",
    "Error loading data": "डेटा लोड करने में त्रुटि",
    // Success Messages
    "Saved successfully": "सफलतापूर्वक सहेजा गया",
    "Updated successfully": "सफलतापूर्वक अपडेट किया गया",
    "Deleted successfully": "सफलतापूर्वक हटाया गया",
    "Uploaded successfully": "सफलतापूर्वक अपलोड किया गया",
    "Changes saved": "परिवर्तन सहेजे गए",
    // Compliance
    "Compliant": "अनुपालनकर्ता",
    "Non-Compliant": "गैर-अनुपालनकर्ता",
    "Under Review": "समीक्षाधीन",
    "Approve": "स्वीकृति दें",
    "Reject": "अस्वीकार करें",
    "Request Changes": "परिवर्तन अनुरोध करें",
    "Audit Trail": "ऑडिट ट्रेल",
    "Violations": "उल्लंघन",
    // IoT Dashboard
    "Devices": "उपकरण",
    "Sensors": "सेंसर",
    "Alerts": "अलर्ट",
    "Status": "स्थिति",
    "Temperature": "तापमान",
    "Pressure": "दबाव",
    "Humidity": "आर्द्रता",
    "Voltage": "वोल्टेज",
    "Online": "ऑनलाइन",
    "Offline": "ऑफ़लाइन",
    "Warning": "चेतावनी",
    "Critical": "गंभीर",
    // Knowledge Graph
    "Nodes": "नोड्स",
    "Connections": "कनेक्शन",
    "Topics": "विषय",
    "People": "लोग",
    "Expand": "विस्तृत करें",
    "Collapse": "समेटें",
    "Export": "निर्यात करें",
    "Zoom In": "ज़ूम इन",
    "Zoom Out": "ज़ूम आउट",
    // Workforce
    "Active": "सक्रिय",
    "Inactive": "निष्क्रिय",
    "On Leave": "छुट्टी पर",
    "Departed": "प्रस्थान किया",
    "View Profile": "प्रोफ़ाइल देखें",
    "Assign Task": "कार्य सौंपें",
    "Send Message": "संदेश भेजें",
    "Department": "विभाग",
    "Role": "भूमिका",
    "Location": "स्थान",
    // Tooltips & Actions
    "Click to expand": "विस्तृत करने के लिए क्लिक करें",
    "Drag to reorder": "पुनः क्रमबद्ध करने के लिए खींचें",
    "Right-click for options": "विकल्पों के लिए राइट-क्लिक करें",
    "Loading...": "लोड हो रहा है...",
    "Refresh": "रीफ्रेश करें",
    "Download": "डाउनलोड करें",
    "Print": "प्रिंट करें",
    "Share": "साझा करें",
    "Copy": "कॉपी करें",
    "Paste": "पेस्ट करें",
    "Duplicate": "डुप्लिकेट करें",
    "More actions": "अधिक क्रियाएं"
  },

  Telugu: {
    "Engineer View": "ఇంజనీర్ వ్యూ",
    "Manager View": "మేనేజర్ వ్యూ",
    "Operator View": "ఆపరేటర్ వ్యూ",
    "Safety Officer View": "సేఫ్టీ ఆఫీసర్ వ్యూ",
    "Maintenance Tech View": "మెయింటెనెన్స్ టెక్ వ్యూ",
    "Quality Inspector View": "క్వాలిటీ ఇన్స్పెక్టర్ వ్యూ",
    "AI Insights": "AI ఇన్సైట్స్",
    "Powered by Gemini": "Gemini ద్వారా శక్తివంతం",
    "Technical Summary": "సాంకేతిక సారాంశం",
    "Key Specifications": "కీలక స్పెసిఫికేషన్స్",
    "Compliance Status": "కంప్లయన్స్ స్థితి",
    "Risk Factors": "రిస్క్ ఫ్యాక్టర్స్",
    "Executive Summary": "ఎగ్జిక్యూటివ్ సారాంశం",
    "Financial Overview": "ఆర్థిక సమీక్ష",
    "Risk Assessment": "రిస్క్ అసెస్మెంట్",
    "Recommended Actions": "సిఫార్సు చర్యలు",
    "Export Summary": "సారాంశం ఎగ్జిపోర్ట్",
    "Share Insights": "ఇన్సైట్స్ షేర్ చేయండి",
    "Regenerate": "పునరుత్పత్తి",
    "View Original": "ఒరిజినల్ చూడండి",
    "Settings": "సెట్టింగ్స్",
    "Language & Region": "భాష & ప్రాంతం",
    "Interface Language": "ఇంటర్ఫేస్ భాష",
    "Select your preferred language for the application interface.": "అప్లికేషన్ ఇంటర్ఫేస్ కోసం మీ ఇష్టమైన భాషను ఎంచుకోండి.",
    "Note: AI Insights language is managed separately within the Document Viewer.": "గమనిక: AI ఇన్సైట్స్ భాష డాక్యుమెంట్ వ్యూయర్లో విడిగా నిర్వహించబడుతుంది.",
    "Select Language": "భాష ఎంచుకోండి",
    "Current": "ప్రస్తుతం",
    "Appearance": "రూపాన్ని",
    "Theme selection (Dark/Light) is currently managed by the system.": "థీమ్ ఎంపిక (డార్క్/లైట్) ప్రస్తుతం సిస్టమ్ ద్వారా నిర్వహించబడుతుంది.",
    "Dashboard": "డ్యాష్‌బోర్డ్",
    "Search": "శోధన",
    "Profile": "ప్రొఫైల్",
    "Logout": "లాగ్అవుట్",
    "Admin Panel": "అడ్మిన్ ప్యానెల్",
    "Language": "భాష",
    "Documents": "పత్రాలు",
    "IoT Dashboard": "IoT డ్యాష్‌బోర్డ్",
    "Knowledge Graph": "నాలెడ్జ్ గ్రాఫ్",
    "AR Visualization": "AR విజువలైజేషన్",
    "Compliance": "కంప్లయన్స్",
    "Features": "ఫీచర్లు",
    "New": "కొత్త",
    "Mission Control": "మిషన్ కంట్రోల్",
    "Workforce": "వర్క్‌ఫోర్స్",
    "Morning Briefing": "మార్నింగ్ బ్రీఫింగ్",
    "Here's what you need to know today": "ఈరోజు మీరు తెలుసుకోవలసినది ఇక్కడ ఉంది",
    "System Status": "సిస్టమ్ స్టేటస్",
    "Operational": "ఆపరేషనల్",
    "Active Nodes": "యాక్టివ్ నోడ్స్",
    "Verification Rate": "వెరిఫికేషన్ రేట్",
    "Pending Review": "పెండింగ్ రివ్యూ",
    "Recent Activity": "ఇటీవలి కార్యకలాపాలు",
    "Upload Document": "డాక్యుమెంట్ అప్‌లోడ్ చేయండి",
    "View": "చూడండి",
    "Upload": "అప్‌లోడ్",
    "Processing": "ప్రాసెసింగ్",
    "Completed": "పూర్తైంది",
    "Failed": "విఫలమైంది"
  },

  Marathi: {
    "Engineer View": "अभियंता दृश्य",
    "Manager View": "व्यवस्थापक दृश्य",
    "Operator View": "ऑपरेटर दृश्य",
    "Safety Officer View": "सुरक्षा अधिकारी दृश्य",
    "Maintenance Tech View": "देखभाल तंत्रज्ञ दृश्य",
    "Quality Inspector View": "गुणवत्ता निरीक्षक दृश्य",
    "AI Insights": "AI इनसाइट्स",
    "Powered by Gemini": "Gemini द्वारे समर्थित",
    "Technical Summary": "तांत्रिक सारांश",
    "Key Specifications": "मुख्य तपशील",
    "Compliance Status": "अनुपालन स्थिती",
    "Risk Factors": "जोखीम घटक",
    "Executive Summary": "कार्यकारी सारांश",
    "Financial Overview": "आर्थिक विहंगावलोकन",
    "Risk Assessment": "जोखीम मूल्यांकन",
    "Recommended Actions": "शिफारस केलेल्या कृती",
    "Export Summary": "सारांश निर्यात करा",
    "Share Insights": "इनसाइट्स शेअर करा",
    "Regenerate": "पुनर्जन्म",
    "View Original": "मूळ पहा",
    "Settings": "सेटिंग्ज",
    "Language & Region": "भाषा आणि प्रदेश",
    "Interface Language": "इंटरफेस भाषा",
    "Select your preferred language for the application interface.": "अॅप्लिकेशन इंटरफेससाठी तुमची पसंतीची भाषा निवडा.",
    "Note: AI Insights language is managed separately within the Document Viewer.": "टीप: AI इनसाइट्स भाषा दस्तऐवज दर्शकामध्ये स्वतंत्रपणे व्यवस्थापित केली जाते.",
    "Select Language": "भाषा निवडा",
    "Current": "वर्तमान",
    "Appearance": "देखावा",
    "Theme selection (Dark/Light) is currently managed by the system.": "थीम निवड (गडद/हलका) सध्या सिस्टमद्वारे व्यवस्थापित केली जाते.",
    "Dashboard": "डॅशबोर्ड",
    "Search": "शोधा",
    "Profile": "प्रोफाइल",
    "Logout": "लॉगआउट",
    "Admin Panel": "प्रशासक पॅनेल",
    "Language": "भाषा",
    "Documents": "दस्तऐवज",
    "IoT Dashboard": "IoT डॅशबोर्ड",
    "Knowledge Graph": "ज्ञान आलेख",
    "AR Visualization": "AR व्हिज्युअलायझेशन",
    "Compliance": "अनुपालन",
    "Features": "वैशिष्ट्ये",
    "New": "नवीन",
    "Mission Control": "मिशन कंट्रोल",
    "Workforce": "कर्मचारी",
    "Morning Briefing": "सकाळची माहिती",
    "Here's what you need to know today": "आज तुम्हाला काय माहित असणे आवश्यक आहे ते येथे आहे",
    "System Status": "प्रणाली स्थिती",
    "Operational": "कार्यरत",
    "Active Nodes": "सक्रिय नोड्स",
    "Verification Rate": "पडताळणी दर",
    "Pending Review": "प्रलंबित पुनरावलोकन",
    "Recent Activity": "अलीकडील क्रियाकलाप",
    "Upload Document": "दस्तऐवज अपलोड करा",
    "View": "पहा",
    "Upload": "अपलोड",
    "Processing": "प्रक्रिया",
    "Completed": "पूर्ण",
    "Failed": "अयशस्वी"
  },

  Tamil: {
    "Engineer View": "பொறியாளர் காட்சி",
    "Manager View": "மேலாளர் காட்சி",
    "Operator View": "இயக்குனர் காட்சி",
    "Safety Officer View": "பாதுகாப்பு அதிகாரி காட்சி",
    "Maintenance Tech View": "பராமரிப்பு தொழில்நுட்ப காட்சி",
    "Quality Inspector View": "தர ஆய்வாளர் காட்சி",
    "AI Insights": "AI நுண்ணறிவு",
    "Powered by Gemini": "Gemini மூலம் இயக்கப்படுகிறது",
    "Technical Summary": "தொழில்நுட்ப சுருக்கம்",
    "Key Specifications": "முக்கிய விவரக்குறிப்புகள்",
    "Compliance Status": "இணக்க நிலை",
    "Risk Factors": "இடர் காரணிகள்",
    "Executive Summary": "நிர்வாக சுருக்கம்",
    "Financial Overview": "நிதி மேலோட்டம்",
    "Risk Assessment": "இடர் மதிப்பீடு",
    "Recommended Actions": "பரிந்துரைக்கப்பட்ட செயல்கள்",
    "Export Summary": "சுருக்கத்தை ஏற்றுமதி செய்",
    "Share Insights": "நுண்ணறிவைப் பகிர்",
    "Regenerate": "மீண்டும் உருவாக்கு",
    "View Original": "அசலைக் காண்க",
    "Settings": "அமைப்புகள்",
    "Language & Region": "மொழி மற்றும் பகுதி",
    "Interface Language": "இடைமுக மொழி",
    "Select your preferred language for the application interface.": "பயன்பாட்டு இடைமுகத்திற்கான உங்களுக்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்.",
    "Note: AI Insights language is managed separately within the Document Viewer.": "குறிப்பு: AI நுண்ணறிவு மொழி ஆவண பார்வையாளருக்குள் தனித்தனியாக நிர்வகிக்கப்படுகிறது.",
    "Select Language": "மொழியைத் தேர்ந்தெடு",
    "Current": "தற்போதைய",
    "Appearance": "தோற்றம்",
    "Theme selection (Dark/Light) is currently managed by the system.": "தீம் தேர்வு (இருள்/ஒளி) தற்போது கணினியால் நிர்வகிக்கப்படுகிறது.",
    "Dashboard": "டாஷ்போர்டு",
    "Search": "தேடு",
    "Profile": "சுயவிவரம்",
    "Logout": "வெளியேறு",
    "Admin Panel": "நிர்வாகப் பலகை",
    "Language": "மொழி",
    "Documents": "ஆவணங்கள்",
    "IoT Dashboard": "IoT டாஷ்போர்டு",
    "Knowledge Graph": "அறிவு வரைபடம்",
    "AR Visualization": "AR காட்சிப்படுத்தல்",
    "Compliance": "இணக்கம்",
    "Features": "அம்சங்கள்",
    "New": "புதிய",
    "Mission Control": "பணி கட்டுப்பாடு",
    "Workforce": "பணியாளர்கள்",
    "Morning Briefing": "காலை விளக்கம்",
    "Here's what you need to know today": "இன்று நீங்கள் தெரிந்து கொள்ள வேண்டியது இதோ",
    "System Status": "கணினி நிலை",
    "Operational": "செயல்பாட்டு",
    "Active Nodes": "செயலில் உள்ள முனைகள்",
    "Verification Rate": "சரிபார்ப்பு விகிதம்",
    "Pending Review": "நிலுவையில் உள்ள ஆய்வு",
    "Recent Activity": "சமீபத்திய செயல்பாடு",
    "Upload Document": "ஆவணத்தைப் பதிவேற்று",
    "View": "காண்க",
    "Upload": "பதிவேற்று",
    "Processing": "செயலாக்கம்",
    "Completed": "முடிந்தது",
    "Failed": "தோல்வி"
  },

  Urdu: {
    "Engineer View": "انجینئر ویو",
    "Manager View": "منیجر ویو",
    "Operator View": "آپریٹر ویو",
    "Safety Officer View": "سیفٹی آفیسر ویو",
    "Maintenance Tech View": "مینٹیننس ٹیک ویو",
    "Quality Inspector View": "کوالٹی انسپکٹر ویو",
    "AI Insights": "AI بصیرت",
    "Powered by Gemini": "Gemini کی طرف سے تقویت یافتہ",
    "Technical Summary": "تکنیکی خلاصہ",
    "Key Specifications": "اہم تفصیلات",
    "Compliance Status": "تعمیل کی حیثیت",
    "Risk Factors": "خطرے کے عوامل",
    "Executive Summary": "ایگزیکٹو خلاصہ",
    "Financial Overview": "مالیاتی جائزہ",
    "Risk Assessment": "خطرے کی تشخیص",
    "Recommended Actions": "تجویز کردہ اقدامات",
    "Export Summary": "خلاصہ برآمد کریں",
    "Share Insights": "بصیرت شیئر کریں",
    "Regenerate": "دوبارہ پیدا کریں",
    "View Original": "اصل دیکھیں",
    "Settings": "ترتیبات",
    "Language & Region": "زبان اور علاقہ",
    "Interface Language": "انٹرفیس زبان",
    "Select your preferred language for the application interface.": "ایپلیکیشن انٹرفیس کے لیے اپنی پسندیدہ زبان منتخب کریں۔",
    "Note: AI Insights language is managed separately within the Document Viewer.": "نوٹ: AI بصیرت کی زبان دستاویز ناظر کے اندر الگ سے منظم کی جاتی ہے۔",
    "Select Language": "زبان منتخب کریں",
    "Current": "موجودہ",
    "Appearance": "ظاہری شکل",
    "Theme selection (Dark/Light) is currently managed by the system.": "تھیم کا انتخاب (گہرا/ہلکا) فی الحال نظام کے ذریعہ منظم کیا جاتا ہے۔",
    "Dashboard": "ڈیش بورڈ",
    "Search": "تلاش کریں",
    "Profile": "پروفائل",
    "Logout": "لاگ آؤٹ",
    "Admin Panel": "ایڈمن پینل",
    "Language": "زبان",
    "Documents": "دستاویزات",
    "IoT Dashboard": "IoT ڈیش بورڈ",
    "Knowledge Graph": "علم کا گراف",
    "AR Visualization": "AR تصوراتی نمائش",
    "Compliance": "تعمیل",
    "Features": "خصوصیات",
    "New": "نیا",
    "Mission Control": "مشن کنٹرول",
    "Workforce": "افرادی قوت",
    "Morning Briefing": "صبح کی بریفنگ",
    "Here's what you need to know today": "یہاں وہ ہے جو آپ کو آج جاننے کی ضرورت ہے",
    "System Status": "سسٹم کی حیثیت",
    "Operational": "آپریشنل",
    "Active Nodes": "فعال نوڈس",
    "Verification Rate": "تصدیق کی شرح",
    "Pending Review": "زیر التواء جائزہ",
    "Recent Activity": "حالیہ سرگرمی",
    "Upload Document": "دستاویز اپ لوڈ کریں",
    "View": "دیکھیں",
    "Upload": "اپ لوڈ",
    "Processing": "پروسیسنگ",
    "Completed": "مکمل",
    "Failed": "ناکام"
  },

  Gujarati: {
    "Engineer View": "એન્જિનિયર વ્યૂ",
    "Manager View": "મેનેજર વ્યૂ",
    "Operator View": "ઓપરેટર વ્યૂ",
    "Safety Officer View": "સેફ્ટી ઓફિસર વ્યૂ",
    "Maintenance Tech View": "મેઈન્ટેનન્સ ટેક વ્યૂ",
    "Quality Inspector View": "ગુણવત્તા નિરીક્ષક વ્યૂ",
    "AI Insights": "AI ઇનસાઇટ્સ",
    "Powered by Gemini": "Gemini દ્વારા સંચાલિત",
    "Technical Summary": "તકનીકી સારાંશ",
    "Key Specifications": "મુખ્ય વિશિષ્ટતાઓ",
    "Compliance Status": "અનુપાલન સ્થિતિ",
    "Risk Factors": "જોખમ પરિબળો",
    "Executive Summary": "કાર્યકારી સારાંશ",
    "Financial Overview": "નાણાકીય વિહંગાવલોકન",
    "Risk Assessment": "જોખમ મૂલ્યાંકન",
    "Recommended Actions": "ભલામણ કરેલ ક્રિયાઓ",
    "Export Summary": "સારાંશ નિકાસ કરો",
    "Share Insights": "ઇનસાઇટ્સ શેર કરો",
    "Regenerate": "પુનર્જનન",
    "View Original": "મૂળ જુઓ",
    "Settings": "સેટિંગ્સ",
    "Language & Region": "ભાષા અને પ્રદેશ",
    "Interface Language": "ઇન્ટરફેસ ભાષા",
    "Select your preferred language for the application interface.": "એપ્લિકેશન ઇન્ટરફેસ માટે તમારી પસંદગીની ભાષા પસંદ કરો.",
    "Note: AI Insights language is managed separately within the Document Viewer.": "નોંધ: AI ઇનસાઇટ્સ ભાષા ડોક્યુમેન્ટ વ્યૂઅરમાં અલગથી સંચાલિત થાય છે.",
    "Select Language": "ભાષા પસંદ કરો",
    "Current": "વર્તમાન",
    "Appearance": "દેખાવ",
    "Theme selection (Dark/Light) is currently managed by the system.": "થીમ પસંદગી (ઘાટો/હલકો) હાલમાં સિસ્ટમ દ્વારા સંચાલિત છે.",
    "Dashboard": "ડેશબોર્ડ",
    "Search": "શોધો",
    "Profile": "પ્રોફાઇલ",
    "Logout": "લૉગઆઉટ",
    "Admin Panel": "એડમિન પેનલ",
    "Language": "ભાષા",
    "Documents": "દસ્તાવેજો",
    "IoT Dashboard": "IoT ડેશબોર્ડ",
    "Knowledge Graph": "જ્ઞાન ગ્રાફ",
    "AR Visualization": "AR વિઝ્યુઅલાઇઝેશન",
    "Compliance": "અનુપાલન",
    "Features": "લક્ષણો",
    "New": "નવું",
    "Mission Control": "મિશન કંટ્રોલ",
    "Workforce": "કાર્યબળ",
    "Morning Briefing": "સવારની બ્રીફિંગ",
    "Here's what you need to know today": "આજે તમારે શું જાણવાની જરૂર છે તે અહીં છે",
    "System Status": "સિસ્ટમ સ્થિતિ",
    "Operational": "કાર્યરત",
    "Active Nodes": "સક્રિય નોડ્સ",
    "Verification Rate": "ચકાસણી દર",
    "Pending Review": "પેન્ડિંગ સમીક્ષા",
    "Recent Activity": "તાજેતરની પ્રવૃત્તિ",
    "Upload Document": "દસ્તાવેજ અપલોડ કરો",
    "View": "જુઓ",
    "Upload": "અપલોડ",
    "Processing": "પ્રક્રિયા",
    "Completed": "પૂર્ણ",
    "Failed": "નિષ્ફળ"
  },

  Kannada: {
    "Engineer View": "ಇಂಜಿನಿಯರ್ ವೀಕ್ಷಣೆ",
    "Manager View": "ಮ್ಯಾನೇಜರ್ ವೀಕ್ಷಣೆ",
    "Operator View": "ಆಪರೇಟರ್ ವೀಕ್ಷಣೆ",
    "Safety Officer View": "ಸೇಫ್ಟಿ ಆಫೀಸರ್ ವೀಕ್ಷಣೆ",
    "Maintenance Tech View": "ಮೇಂಟಿನೆನ್ಸ್ ಟೆಕ್ ವೀಕ್ಷಣೆ",
    "Quality Inspector View": "ಗುಣಮಟ್ಟ ತಪಾಸಣೆ ವೀಕ್ಷಣೆ",
    "AI Insights": "AI ಒಳನೋಟಗಳು",
    "Powered by Gemini": "Gemini ಮೂಲಕ ನಡೆಸಲ್ಪಡುತ್ತಿದೆ",
    "Technical Summary": "ತಾಂತ್ರಿಕ ಸಾರಾಂಶ",
    "Key Specifications": "ಪ್ರಮುಖ ವಿಶೇಷಣಗಳು",
    "Compliance Status": "ಅನುಸರಣೆ ಸ್ಥಿತಿ",
    "Risk Factors": "ಅಪಾಯ ಅಂಶಗಳು",
    "Executive Summary": "ಕಾರ್ಯನಿರ್ವಾಹಕ ಸಾರಾಂಶ",
    "Financial Overview": "ಹಣಕಾಸು ಅವಲೋಕನ",
    "Risk Assessment": "ಅಪಾಯ ಮೌಲ್ಯಮಾಪನ",
    "Recommended Actions": "ಶಿಫಾರಸ್ಸು ಮಾಡಿದ ಕ್ರಮಗಳು",
    "Export Summary": "ಸಾರಾಂಶವನ್ನು ರಫ್ತು ಮಾಡು",
    "Share Insights": "ಒಳನೋಟಗಳನ್ನು ಹಂಚಿ",
    "Regenerate": "ಪುನರುತ್ಪಾದಿಸಿ",
    "View Original": "ಮೂಲವನ್ನು ವೀಕ್ಷಿಸಿ",
    "Settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    "Language & Region": "ಭಾಷೆ ಮತ್ತು ಪ್ರದೇಶ",
    "Interface Language": "ಇಂಟರ್ಫೇಸ್ ಭಾಷೆ",
    "Select your preferred language for the application interface.": "ಅಪ್ಲಿಕೇಶನ್ ಇಂಟರ್ಫೇಸ್‌ಗಾಗಿ ನಿಮ್ಮ ಬಯಸಿದ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    "Note: AI Insights language is managed separately within the Document Viewer.": "ಗಮನಿಸಿ: AI ಒಳನೋಟಗಳ ಭಾಷೆಯನ್ನು ದಾಖಲೆ ವೀಕ್ಷಕದಲ್ಲಿ ಪ್ರತ್ಯೇಕವಾಗಿ ನಿರ್ವಹಿಸಲಾಗುತ್ತದೆ.",
    "Select Language": "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "Current": "ಪ್ರಸ್ತುತ",
    "Appearance": "ನೋಟ",
    "Theme selection (Dark/Light) is currently managed by the system.": "ಥೀಮ್ ಆಯ್ಕೆ (ಗಾಢ/ಹಗುರ) ಪ್ರಸ್ತುತ ವ್ಯವಸ್ಥೆಯಿಂದ ನಿರ್ವಹಿಸಲ್ಪಡುತ್ತಿದೆ.",
    "Dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "Search": "ಹುಡುಕಿ",
    "Profile": "ಪ್ರೊಫೈಲ್",
    "Logout": "ಲಾಗ್ ಔಟ್",
    "Admin Panel": "ಅಡ್ಮಿನ್ ಪ್ಯಾನೆಲ್",
    "Language": "ಭಾಷೆ",
    "Documents": "ದಾಖಲೆಗಳು",
    "IoT Dashboard": "IoT ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "Knowledge Graph": "ಜ್ಞಾನ ಗ್ರಾಫ್",
    "AR Visualization": "AR ದೃಶ್ಯೀಕರಣ",
    "Compliance": "ಅನುಸರಣೆ",
    "Features": "ವೈಶಿಷ್ಟ್ಯಗಳು",
    "New": "ಹೊಸ",
    "Mission Control": "ಮಿಷನ್ ಕಂಟ್ರೋಲ್",
    "Workforce": "ಕಾರ್ಯಪಡೆ",
    "Morning Briefing": "ಮಾರ್ನಿಂಗ್ ಬ್ರೀಫಿಂಗ್",
    "Here's what you need to know today": "ಇಂದು ನೀವು ತಿಳಿದುಕೊಳ್ಳಬೇಕಾದದ್ದು ಇಲ್ಲಿದೆ",
    "System Status": "ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ",
    "Operational": "ಕಾರ್ಯಾತ್ಮಕ",
    "Active Nodes": "ಸಕ್ರಿಯ ನೋಡ್‌ಗಳು",
    "Verification Rate": "ಪರಿಶೀಲನೆ ದರ",
    "Pending Review": "ಬಾಕಿ ವಿಮರ್ಶೆ",
    "Recent Activity": "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    "Upload Document": "ದಾಖಲೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "View": "ವೀಕ್ಷಿಸಿ",
    "Upload": "ಅಪ್‌ಲೋಡ್",
    "Processing": "ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ",
    "Completed": "ಪೂರ್ಣಗೊಂಡಿದೆ",
    "Failed": "ವಿಫಲವಾಗಿದೆ"
  },

  Malayalam: {
    "Engineer View": "എൻജിനീയർ കാഴ്ച",
    "Manager View": "മാനേജർ കാഴ്ച",
    "Operator View": "ഓപ്പറേറ്റർ കാഴ്ച",
    "Safety Officer View": "സേഫ്റ്റി ഓഫീസർ കാഴ്ച",
    "Maintenance Tech View": "മെയിന്റനൻസ് ടെക് കാഴ്ച",
    "Quality Inspector View": "ഗുണനിലവാര പരിശോധകൻ കാഴ്ച",
    "AI Insights": "AI ഇൻസൈറ്റ്‌സ്",
    "Powered by Gemini": "Gemini വഴി നൽകുന്നു",
    "Technical Summary": "സാങ്കേതിക സംഗ്രഹം",
    "Key Specifications": "പ്രധാന സവിശേഷതകൾ",
    "Compliance Status": "അനുസരണ നില",
    "Risk Factors": "അപകടസാദ്ധ്യത ഘടകങ്ങൾ",
    "Executive Summary": "എക്‌സിക്യൂട്ടീവ് സംഗ്രഹം",
    "Financial Overview": "സാമ്പത്തിക അവലോകനം",
    "Risk Assessment": "അപകടസാദ്ധ്യത വിലയിരുത്തൽ",
    "Recommended Actions": "ശുപാർശചെയ്ത നടപടികൾ",
    "Export Summary": "സംഗ്രഹം എക്‌സ്‌പോർട്ട് ചെയ്യുക",
    "Share Insights": "ഇൻസൈറ്റ്‌സ് പങ്കിടുക",
    "Regenerate": "പുനർനിർമ്മിക്കുക",
    "View Original": "യഥാർത്ഥം കാണുക",
    "Settings": "ക്രമീകരണങ്ങൾ",
    "Language & Region": "ഭാഷയും പ്രദേശവും",
    "Interface Language": "ഇന്റർഫേസ് ഭാഷ",
    "Select your preferred language for the application interface.": "ആപ്ലിക്കേഷൻ ഇന്റർഫേസിനായി നിങ്ങളുടെ ഇഷ്ടപ്പെട്ട ഭാഷ തിരഞ്ഞെടുക്കുക.",
    "Note: AI Insights language is managed separately within the Document Viewer.": "കുറിപ്പ്: AI ഇൻസൈറ്റ്‌സ് ഭാഷ ഡോക്യുമെന്റ് വ്യൂവറിൽ പ്രത്യേകം നിയന്ത്രിക്കപ്പെടുന്നു.",
    "Select Language": "ഭാഷ തിരഞ്ഞെടുക്കുക",
    "Current": "നിലവിലുള്ളത്",
    "Appearance": "രൂപം",
    "Theme selection (Dark/Light) is currently managed by the system.": "തീം തിരഞ്ഞെടുപ്പ് (ഇരുണ്ട/വെളിച്ചം) നിലവിൽ സിസ്റ്റം നിയന്ത്രിക്കുന്നു.",
    "Dashboard": "ഡാഷ്‌ബോർഡ്",
    "Search": "തിരയുക",
    "Profile": "പ്രൊഫൈൽ",
    "Logout": "ലോഗ് ഔട്ട്",
    "Admin Panel": "അഡ്മിൻ പാനൽ",
    "Language": "ഭാഷ",
    "Documents": "രേഖകൾ",
    "IoT Dashboard": "IoT ഡാഷ്‌ബോർഡ്",
    "Knowledge Graph": "നോളജ് ഗ്രാഫ്",
    "AR Visualization": "AR ദൃശ്യവൽക്കരണം",
    "Compliance": "അനുസരണം",
    "Features": "സവിശേഷതകൾ",
    "New": "പുതിയത്",
    "Mission Control": "മിഷൻ കൺട്രോൾ",
    "Workforce": "തൊഴിലാളികൾ",
    "Morning Briefing": "രാവിലെ ബ്രീഫിംഗ്",
    "Here's what you need to know today": "ഇന്ന് നിങ്ങൾ അറിയേണ്ടത് ഇതാ",
    "System Status": "സിസ്റ്റം നില",
    "Operational": "പ്രവർത്തനം",
    "Active Nodes": "സജീവ നോഡുകൾ",
    "Verification Rate": "സ്ഥിരീകരണ നിരക്ക്",
    "Pending Review": "അവലോകനം ശേഷിക്കുന്നു",
    "Recent Activity": "സമീപകാല പ്രവർത്തനം",
    "Upload Document": "രേഖ അപ്‌ലോഡ് ചെയ്യുക",
    "View": "കാണുക",
    "Upload": "അപ്‌ലോഡ്",
    "Processing": "പ്രോസസ്സിംഗ്",
    "Completed": "പൂർത്തിയായി",
    "Failed": "പരാജയപ്പെട്ടു"
  },

  Odia: {
    "Engineer View": "ଇଞ୍ଜିନିୟର ଦୃଶ୍ୟ",
    "Manager View": "ମ୍ୟାନେଜର ଦୃଶ୍ୟ",
    "Operator View": "ଅପରେଟର ଦୃଶ୍ୟ",
    "Safety Officer View": "ସେଫ୍ଟି ଅଫିସର ଦୃଶ୍ୟ",
    "Maintenance Tech View": "ରକ୍ଷଣାବେକ୍ଷଣ ଟେକ ଦୃଶ୍ୟ",
    "Quality Inspector View": "ଗୁଣବତ୍ତା ନିରୀକ୍ଷକ ଦୃଶ୍ୟ",
    "AI Insights": "AI ଇନସାଇଟ୍ସ",
    "Powered by Gemini": "Gemini ଦ୍ୱାରା ଚାଳିତ",
    "Technical Summary": "ଯାନ୍ତ୍ରିକ ସାରାଂଶ",
    "Key Specifications": "ମୁଖ୍ୟ ନିର୍ଦ୍ଦିଷ୍ଟତା",
    "Compliance Status": "ଅନୁପାଳନ ସ୍ଥିତି",
    "Risk Factors": "ବିପଦ କାରକ",
    "Executive Summary": "କାର୍ଯ୍ୟକାରୀ ସାରାଂଶ",
    "Financial Overview": "ଆର୍ଥିକ ସମୀକ୍ଷା",
    "Risk Assessment": "ବିପଦ ମୂଲ୍ୟାଙ୍କନ",
    "Recommended Actions": "ସୁପାରିଶ କରାଯାଇଥିବା କାର୍ଯ୍ୟ",
    "Export Summary": "ସାରାଂଶ ରପ୍ତାନି କରନ୍ତୁ",
    "Share Insights": "ଇନସାଇଟ୍ସ ଶେୟାର କରନ୍ତୁ",
    "Regenerate": "ପୁନର୍ଜନ୍ମ",
    "View Original": "ମୂଳ ଦେଖନ୍ତୁ",
    "Settings": "ସେଟିଂସ୍",
    "Language & Region": "ଭାଷା ଏବଂ ଅଞ୍ଚଳ",
    "Interface Language": "ଇଣ୍ଟରଫେସ୍ ଭାଷା",
    "Select your preferred language for the application interface.": "ଆପ୍ଲିକେସନ୍ ଇଣ୍ଟରଫେସ୍ ପାଇଁ ଆପଣଙ୍କର ପସନ୍ଦର ଭାଷା ବାଛନ୍ତୁ।",
    "Note: AI Insights language is managed separately within the Document Viewer.": "ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ: AI ଇନସାଇଟ୍ସ ଭାଷା ଡକ୍ୟୁମେଣ୍ଟ ଭିউୟାରରେ ଅଲଗାରେ ପରିଚାଳିତ ହୁଏ।",
    "Select Language": "ଭାଷା ବାଛନ୍ତୁ",
    "Current": "ବର୍ତ୍ତମାନ",
    "Appearance": "ରୂପ",
    "Theme selection (Dark/Light) is currently managed by the system.": "ଥିମ୍ ଚୟନ (ଗା Dark/ହାଲୁକା) ବର୍ତ୍ତମାନ ସିଷ୍ଟମ୍ ଦ୍ୱାରା ପରିଚାଳିତ ହୁଏ।",
    "Dashboard": "ଡ୍ୟାସବୋର୍ଡ",
    "Search": "ଖୋଜନ୍ତୁ",
    "Profile": "ପ୍ରୋଫାଇଲ୍",
    "Logout": "ଲଗଆଉଟ୍",
    "Admin Panel": "ଆଡମିନ୍ ପ୍ୟାନେଲ୍",
    "Language": "ଭାଷା",
    "Documents": "ଡକ୍ୟୁମେଣ୍ଟସ୍",
    "IoT Dashboard": "IoT ଡ୍ୟାସବୋର୍ଡ",
    "Knowledge Graph": "ଜ୍ଞାନ ଗ୍ରାଫ୍",
    "AR Visualization": "AR ଭିଜୁଆଲାଇଜେସନ୍",
    "Compliance": "ଅନୁପାଳନ",
    "Features": "ବୈଶିଷ୍ଟ୍ୟଗୁଡ଼ିକ",
    "New": "ନୂତନ",
    "Mission Control": "ମିଶନ୍ କଣ୍ଟ୍ରୋଲ୍",
    "Workforce": "କର୍ମୀବାହିନୀ",
    "Morning Briefing": "ସକାଳର ବ୍ରିଫିଂ",
    "Here's what you need to know today": "ଆଜି ଆପଣଙ୍କୁ ଜାଣିବା ଆବଶ୍ୟକ ତାହା ଏଠାରେ ଅଛି",
    "System Status": "ସିଷ୍ଟମ୍ ସ୍ଥିତି",
    "Operational": "କାର୍ଯ୍ୟକ୍ଷମ",
    "Active Nodes": "ସକ୍ରିୟ ନୋଡ୍",
    "Verification Rate": "ଯାଞ୍ଚ ହାର",
    "Pending Review": "ଅପେକ୍ଷିତ ସମୀକ୍ଷା",
    "Recent Activity": "ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ",
    "Upload Document": "ଡକ୍ୟୁମେଣ୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ",
    "View": "ଦେଖନ୍ତୁ",
    "Upload": "ଅପଲୋଡ୍",
    "Processing": "ପ୍ରକ୍ରିୟାକରଣ",
    "Completed": "ସମ୍ପୂର୍ଣ୍ଣ",
    "Failed": "ବିଫଳ"
  },

  Punjabi: {
    "Engineer View": "ਇੰਜੀਨੀਅਰ ਵਿਊ",
    "Manager View": "ਮੈਨੇਜਰ ਵਿਊ",
    "Operator View": "ਆਪਰੇਟਰ ਵਿਊ",
    "Safety Officer View": "ਸੇਫਟੀ ਆਫੀਸਰ ਵਿਊ",
    "Maintenance Tech View": "ਮੇਨਟੇਨੈਂਸ ਟੈਕ ਵਿਊ",
    "Quality Inspector View": "ਗੁਣਵੱਤਾ ਨਿਰੀਖਕ ਵਿਊ",
    "AI Insights": "AI ਇਨਸਾਈਟਸ",
    "Powered by Gemini": "Gemini ਦੁਆਰਾ ਸੰਚਾਲਿਤ",
    "Technical Summary": "ਤਕਨੀਕੀ ਸਾਰ",
    "Key Specifications": "ਮੁੱਖ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
    "Compliance Status": "ਪਾਲਣਾ ਸਥਿਤੀ",
    "Risk Factors": "ਜੋਖਮ ਕਾਰਕ",
    "Executive Summary": "ਕਾਰਜਕਾਰੀ ਸਾਰ",
    "Financial Overview": "ਵਿੱਤੀ ਸੰਖੇਪ",
    "Risk Assessment": "ਜੋਖਮ ਮੁਲਾਂਕਣ",
    "Recommended Actions": "ਸਿਫਾਰਸ਼ ਕੀਤੀਆਂ ਕਾਰਵਾਈਆਂ",
    "Export Summary": "ਸਾਰ ਨਿਰਯਾਤ ਕਰੋ",
    "Share Insights": "ਇਨਸਾਈਟਸ ਸਾਂਝੀਆਂ ਕਰੋ",
    "Regenerate": "ਮੁੜ ਤਿਆਰ ਕਰੋ",
    "View Original": "ਅਸਲ ਦੇਖੋ",
    "Settings": "ਸੈਟਿੰਗਜ਼",
    "Language & Region": "ਭਾਸ਼ਾ ਅਤੇ ਖੇਤਰ",
    "Interface Language": "ਇੰਟਰਫੇਸ ਭਾਸ਼ਾ",
    "Select your preferred language for the application interface.": "ਐਪਲੀਕੇਸ਼ਨ ਇੰਟਰਫੇਸ ਲਈ ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ।",
    "Note: AI Insights language is managed separately within the Document Viewer.": "ਨੋਟ: AI ਇਨਸਾਈਟਸ ਭਾਸ਼ਾ ਨੂੰ ਦਸਤਾਵੇਜ਼ ਦਰਸ਼ਕ ਦੇ ਅੰਦਰ ਵੱਖਰੇ ਤੌਰ 'ਤੇ ਪ੍ਰਬੰਧਿਤ ਕੀਤਾ ਗਿਆ ਹੈ।",
    "Select Language": "ਭਾਸ਼ਾ ਚੁਣੋ",
    "Current": "ਵਰਤਮਾਨ",
    "Appearance": "ਦਿੱਖ",
    "Theme selection (Dark/Light) is currently managed by the system.": "ਥੀਮ ਚੋਣ (ਹਨੇਰਾ/ਰੋਸ਼ਨੀ) ਇਸ ਸਮੇਂ ਸਿਸਟਮ ਦੁਆਰਾ ਪ੍ਰਬੰਧਿਤ ਕੀਤੀ ਜਾਂਦੀ ਹੈ।",
    "Dashboard": "ਡੈਸ਼ਬੋਰਡ",
    "Search": "ਖੋਜੋ",
    "Profile": "ਪ੍ਰੋਫਾਈਲ",
    "Logout": "ਲੌਗਆਉਟ",
    "Admin Panel": "ਐਡਮਿਨ ਪੈਨਲ",
    "Language": "ਭਾਸ਼ਾ",
    "Documents": "ਦਸਤਾਵੇਜ਼",
    "IoT Dashboard": "IoT ਡੈਸ਼ਬੋਰਡ",
    "Knowledge Graph": "ਗਿਆਨ ਗ੍ਰਾਫ",
    "AR Visualization": "AR ਵਿਜ਼ੂਅਲਾਈਜ਼ੇਸ਼ਨ",
    "Compliance": "ਪਾਲਣਾ",
    "Features": "ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
    "New": "ਨਵਾਂ",
    "Mission Control": "ਮਿਸ਼ਨ ਕੰਟਰੋਲ",
    "Workforce": "ਕਰਮਚਾਰੀ",
    "Morning Briefing": "ਸਵੇਰ ਦੀ ਬ੍ਰੀਫਿੰਗ",
    "Here's what you need to know today": "ਇਹ ਉਹ ਹੈ ਜੋ ਤੁਹਾਨੂੰ ਅੱਜ ਜਾਣਨ ਦੀ ਲੋੜ ਹੈ",
    "System Status": "ਸਿਸਟਮ ਸਥਿਤੀ",
    "Operational": "ਸੰਚਾਲਨ",
    "Active Nodes": "ਸਰਗਰਮ ਨੋਡਸ",
    "Verification Rate": "ਪ੍ਰਮਾਣਿਕਤਾ ਦਰ",
    "Pending Review": "ਲੰਬਿਤ ਸਮੀਖਿਆ",
    "Recent Activity": "ਹਾਲੀਆ ਗਤੀਵਿਧੀ",
    "Upload Document": "ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ",
    "View": "ਵੇਖੋ",
    "Upload": "ਅੱਪਲੋਡ",
    "Processing": "ਪ੍ਰੋਸੈਸਿੰਗ",
    "Completed": "ਪੂਰਾ",
    "Failed": "ਅਸਫਲ"
  },

  Assamese: {
    "Engineer View": "অভিযন্তা দৃশ্য",
    "Manager View": "পৰিচালক দৃশ্য",
    "Operator View": "অপাৰেটৰ দৃশ্য",
    "Safety Officer View": "সুৰক্ষা বিষয়া দৃশ্য",
    "Maintenance Tech View": "ৰক্ষণাবেক্ষণ টেক দৃশ্য",
    "Quality Inspector View": "গুণমান পৰিদৰ্শক দৃশ্য",
    "AI Insights": "AI অন্তদৃষ্টি",
    "Powered by Gemini": "Gemini দ্বাৰা চালিত",
    "Technical Summary": "কাৰিকৰী সাৰাংশ",
    "Key Specifications": "মুখ্য নিৰ্দিষ্টতা",
    "Compliance Status": "অনুপালন স্থিতি",
    "Risk Factors": "বিপদ কাৰক",
    "Executive Summary": "কাৰ্যকৰী সাৰাংশ",
    "Financial Overview": "বিত্তীয় অৱলোকন",
    "Risk Assessment": "বিপদ মূল্যায়ন",
    "Recommended Actions": "পৰামৰ্শ দিয়া কাৰ্য",
    "Export Summary": "সাৰাংশ ৰপ্তানি কৰক",
    "Share Insights": "অন্তদৃষ্টি শ্বেয়াৰ কৰক",
    "Regenerate": "পুনৰ উৎপন্ন কৰক",
    "View Original": "মূল চাওক",
    "Settings": "ছেটিংছ",
    "Language & Region": "ভাষা আৰু অঞ্চল",
    "Interface Language": "ইণ্টাৰফেচ ভাষা",
    "Select your preferred language for the application interface.": "এপ্লিকেশ্যন ইণ্টাৰফেচৰ বাবে আপোনাৰ পছন্দৰ ভাষা নিৰ্বাচন কৰক।",
    "Note: AI Insights language is managed separately within the Document Viewer.": "টোকা: AI অন্তদৃষ্টি ভাষা নথিপত্ৰ দৰ্শকৰ ভিতৰত পৃথকভাৱে পৰিচালিত হয়।",
    "Select Language": "ভাষা নিৰ্বাচন কৰক",
    "Current": "বৰ্তমান",
    "Appearance": "উপস্থিতি",
    "Theme selection (Dark/Light) is currently managed by the system.": "থিম নিৰ্বাচন (আন্ধাৰ/পোহৰ) বৰ্তমান চিস্টেমদ্বাৰা পৰিচালিত হয়।",
    "Dashboard": "ড্যাশ্বব'ৰ্ড",
    "Search": "সন্ধান কৰক",
    "Profile": "প্ৰফাইল",
    "Logout": "লগআউট",
    "Admin Panel": "এডমিন পেনেল",
    "Language": "ভাষা",
    "Documents": "নথিপত্'ৰ",
    "IoT Dashboard": "IoT ড্যাশ্বব'ৰ্ড",
    "Knowledge Graph": "জ্ঞান গ্ৰাফ",
    "AR Visualization": "AR ভিজুৱেলাইজেশ্বন",
    "Compliance": "অনুপালন",
    "Features": "বৈশিষ্ট্যসমূহ",
    "New": "নতুন",
    "Mission Control": "মিশ্বন কণ্ট্ৰোল",
    "Workforce": "কৰ্মশক্তি",
    "Morning Briefing": "ৰাতিপুৱাৰ সংক্ষিপ্ত বৰ্ণনা",
    "Here's what you need to know today": "আজি আপুনি জানিব লগীয়া কথা ইয়াত আছে",
    "System Status": "চিস্টেম স্থিতি",
    "Operational": "কাৰ্যক্ষম",
    "Active Nodes": "সক্ৰিয় ন'ডসমূহ",
    "Verification Rate": "পৰীক্ষা হাৰ",
    "Pending Review": "লম্বিত সমীক্ষা",
    "Recent Activity": "শেহতীয়া কাৰ্যকলাপ",
    "Upload Document": "নথিপত্ৰ আপল'ড কৰক",
    "View": "চাওক",
    "Upload": "আপল'ড",
    "Processing": "প্ৰক্ৰিয়াকৰণ",
    "Completed": "সম্পূৰ্ণ",
    "Failed": "বিফল"
  },

  Bengali: {
    "Engineer View": "ইঞ্জিনিয়ার ভিউ",
    "Manager View": "ম্যানেজার ভিউ",
    "Operator View": "অপারেটর ভিউ",
    "Safety Officer View": "সেফটি অফিসার ভিউ",
    "Maintenance Tech View": "মেইনটেনেন্স টেক ভিউ",
    "Quality Inspector View": "কোয়ালিটি ইন্সপেক্টর ভিউ",
    "AI Insights": "AI ইনসাইট",
    "Powered by Gemini": "Gemini দ্বারা চালিত",
    "Technical Summary": "প্রযুক্তিগত সারসংক্ষেপ",
    "Key Specifications": "মূল স্পেসিফিকেশন",
    "Compliance Status": "সম্মতি স্ট্যাটাস",
    "Risk Factors": "ঝুঁকির কারণ",
    "Executive Summary": "নির্বাহী সারসংক্ষেপ",
    "Financial Overview": "আর্থিক সংক্ষিপ্তবিবরণ",
    "Risk Assessment": "ঝুঁকি মূল্যায়ন",
    "Recommended Actions": "প্রস্তাবিত পদক্ষেপ",
    "Export Summary": "রপ্তানি সারসংক্ষেপ",
    "Share Insights": "ইনসাইট শেয়ার করুন",
    "Regenerate": "পুনরুৎপাদন",
    "View Original": "মূল দেখুন",
    "Settings": "সেটিংস",
    "Language & Region": "ভাষা এবং অঞ্চল",
    "Interface Language": "ইন্টারফেস ভাষা",
    "Select your preferred language for the application interface.": "অ্যাপ্লিকেশন ইন্টারফেসের জন্য আপনার পছন্দের ভাষা নির্বাচন করুন।",
    "Note: AI Insights language is managed separately within the Document Viewer.": "নোট: AI ইনসাইট ভাষা ডকুমেন্ট ভিউয়ারের মধ্যে আলাদাভাবে পরিচালিত হয়।",
    "Select Language": "ভাষা নির্বাচন করুন",
    "Current": "বর্তমান",
    "Appearance": "চেহারা",
    "Theme selection (Dark/Light) is currently managed by the system.": "থিম নির্বাচন (ডার্ক/লাইট) বর্তমানে সিস্টেম দ্বারা পরিচালিত হয়।",
    "Dashboard": "ড্যাশবোর্ড",
    "Search": "অনুসন্ধান",
    "Profile": "প্রোফাইল",
    "Logout": "লগ আউট",
    "Admin Panel": "অ্যাডমিন প্যানেল",
    "Language": "ভাষা",
    "Documents": "নথি",
    "IoT Dashboard": "IoT ড্যাশবোর্ড",
    "Knowledge Graph": "জ্ঞান গ্রাফ",
    "AR Visualization": "AR ভিজুয়ালাইজেশন",
    "Compliance": "সম্মতি",
    "Features": "বৈশিষ্ট্য",
    "New": "নতুন",
    "Mission Control": "মিশন কন্ট্রোল",
    "Workforce": "কর্মীবাহিনী",
    "Morning Briefing": "সকালের ব্রিফিং",
    "Here's what you need to know today": "আজ আপনাকে যা জানতে হবে",
    "System Status": "সিস্টেম স্ট্যাটাস",
    "Operational": "অপারেশনাল",
    "Active Nodes": "সক্রিয় নোড",
    "Verification Rate": "যাচাইকরণ হার",
    "Pending Review": "পর্যালোচনা মুলতুবি",
    "Recent Activity": "সাম্প্রতিক কার্যকলাপ",
    "Upload Document": "ডকুমেন্ট আপলোড করুন",
    "View": "দেখুন",
    "Upload": "আপলোড",
    "Processing": "প্রক্রিয়াকরণ",
    "Completed": "সম্পন্ন",
    "Failed": "ব্যর্থ"
  }
  // Add other languages as needed, defaulting to English for missing keys
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("English");

  // Load language from local storage on mount
  useEffect(() => {
    const savedLang = localStorage.getItem('klens-language');
    // Validate saved language
    const isValidLang = SUPPORTED_LANGUAGES.some(l => l.value === savedLang);

    if (savedLang && isValidLang) {
      setLanguage(savedLang as Language);
    } else {
      // Force default to English if invalid or missing
      setLanguage("English");
      localStorage.setItem('klens-language', "English");
    }
  }, []);

  // Save language to local storage on change
  useEffect(() => {
    if (language) {
      localStorage.setItem('klens-language', language);
    }
  }, [language]);

  const t = (key: string, defaultText: string) => {
    const langData = translations[language as keyof typeof translations];
    if (langData && langData[key as keyof typeof langData]) {
      return langData[key as keyof typeof langData];
    }
    return defaultText;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const SUPPORTED_LANGUAGES: { value: Language; label: string }[] = [
  { value: "English", label: "English" },
  { value: "Hindi", label: "Hindi (हिंदी)" },
  { value: "Bengali", label: "Bengali (বাংলা)" },
  { value: "Telugu", label: "Telugu (తెలుగు)" },
  { value: "Marathi", label: "Marathi (मराठी)" },
  { value: "Tamil", label: "Tamil (தமிழ்)" },
  { value: "Urdu", label: "Urdu (اردو)" },
  { value: "Gujarati", label: "Gujarati (ગુજરાતી)" },
  { value: "Kannada", label: "Kannada (ಕನ್ನಡ)" },
  { value: "Malayalam", label: "Malayalam (മലയാളം)" },
  { value: "Odia", label: "Odia (ଓଡ଼ିଆ)" },
  { value: "Punjabi", label: "Punjabi (ਪੰਜਾਬੀ)" },
  { value: "Assamese", label: "Assamese (অসমীয়া)" },
];
